import type {Metadata} from "next";
import {Inter} from "next/font/google";
// import "./globals.css";
// import UserProvider from "@/app/context/username";
import {createServerComponentClient} from '@supabase/auth-helpers-nextjs';
import {cookies} from 'next/headers';


import '@/app/globals.css';
import AuthProvider from "@/components/AuthProvider";
import NavBar from "@/components/NavBar/NavBar";
import {redirect} from "next/navigation";
import Projects from "@/app/projects/page";

const inter = Inter({subsets: ["latin"]});

// do not cache this layout
export const revalidate = 0;

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function ProjectsLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    const supabase = createServerComponentClient({cookies});

    const {
        data: {user},
    } = await supabase.auth.getUser();

    if (!user) {
        redirect('/sign-in');
    }

    return (
        <div className="">
            <AuthProvider accessToken={session?.access_token}>{children}</AuthProvider>
                <Projects supbase={supabase}>{children}</Projects>
        </div>
    );
}
